import type { Theme } from "./types";

export const THEMES: Theme[] = [
  {
    key: "meridian",
    name: "Meridian",
    blurb:
      "The neutral default. Reads as a tool rather than a party — right for work trips and mixed groups.",
    wordmark: "Meridian",
    typeNote: "Instrument · DM Mono",
    strapline: "Five of us, five nights",
    countdown: "Today",
    dayTitle: "Landing and the Loop",
    tag: "Restaurant",
    bookingLabel: "Table booked",
    itemNote:
      "Deep dish takes 45 minutes to bake — order it the second you sit down, before drinks even arrive.",
    cta: "Add to this day",
    secondary: "Decisions",
    fontDisplay: "'Instrument Serif', serif",
    fontSans: "'Instrument Sans', sans-serif",
    fontMono: "'DM Mono', monospace",
    wordTrack: ".01em",
    bg: "#F2F1EC",
    card: "#FDFDFC",
    strip: "#F5F5F0",
    line: "#E4E4DD",
    ink: "#14171A",
    body: "#5E635D",
    meta: "#6E736D",
    headBg: "#14171A",
    headInk: "#F2F1EC",
    headMeta: "#8A9088",
    avatarBg: "#262A2D",
    accent: "oklch(0.52 0.13 285)",
    accentInk: "oklch(0.45 0.13 285)",
    btnInk: "#FDFDFC",
    tagBg: "oklch(0.96 0.03 155)",
    tagInk: "oklch(0.42 0.11 155)",
    okInk: "oklch(0.45 0.11 155)",
    warnBg: "oklch(0.96 0.04 60)",
    warnInk: "oklch(0.5 0.13 60)",
    star: "oklch(0.68 0.15 70)",
    photoFill:
      "repeating-linear-gradient(135deg, #EDEDE6 0 10px, #F5F5F0 10px 20px)",
    frameRadius: "18px",
    cardRadius: "14px",
    pillRadius: "10px",
    chipRadius: "12px",
    swatches: ["#14171A", "oklch(0.52 0.13 285)", "oklch(0.52 0.11 155)"],
  },
  {
    key: "cherry",
    name: "Cherry Club",
    blurb:
      "Bachelorette and hen weekends. Cream over cherry, coral actions, softer language — sleeps instead of days.",
    wordmark: "Cherry Club",
    typeNote: "Playfair · Jost",
    strapline: "Five of us, one last hurrah",
    countdown: "Today!",
    dayTitle: "Landing, then deep dish",
    tag: "Dinner",
    bookingLabel: "Table's ours",
    itemNote:
      "Deep dish takes 45 minutes to bake — order it dead first, before anyone even sits down properly.",
    cta: "Add something",
    secondary: "To settle",
    fontDisplay: "'Playfair Display', serif",
    fontSans: "'Jost', sans-serif",
    fontMono: "'Jost', sans-serif",
    wordTrack: ".02em",
    bg: "#FDF3F1",
    card: "#FFFFFF",
    strip: "#FBEBE9",
    line: "#F2DAD7",
    ink: "#3A1620",
    body: "#6E4A52",
    meta: "#946C74",
    headBg: "#8E1F35",
    headInk: "#FFF3F0",
    headMeta: "#E3AEB4",
    avatarBg: "#A63348",
    accent: "oklch(0.62 0.19 20)",
    accentInk: "oklch(0.5 0.17 20)",
    btnInk: "#FFFFFF",
    tagBg: "oklch(0.95 0.04 20)",
    tagInk: "oklch(0.5 0.15 20)",
    okInk: "oklch(0.52 0.1 150)",
    warnBg: "oklch(0.96 0.05 50)",
    warnInk: "oklch(0.52 0.14 45)",
    star: "oklch(0.7 0.16 60)",
    photoFill:
      "repeating-linear-gradient(135deg, #F7E2DF 0 10px, #FBEDEB 10px 20px)",
    frameRadius: "22px",
    cardRadius: "18px",
    pillRadius: "999px",
    chipRadius: "999px",
    swatches: ["#8E1F35", "oklch(0.62 0.19 20)", "oklch(0.7 0.16 60)"],
  },
  {
    key: "dispatch",
    name: "Dispatch",
    blurb:
      "Boys' trips and anything logistics-heavy. Slate and high-vis lime, hard corners, all-caps labels, T-minus countdowns.",
    wordmark: "DISPATCH",
    typeNote: "Archivo · JetBrains",
    strapline: "5 pax · 5 nights · The Loop",
    countdown: "T–0",
    dayTitle: "Landing and the Loop",
    tag: "MESS",
    bookingLabel: "BOOKED",
    itemNote:
      "Deep dish takes 45 min to bake. Order on arrival, 19:30, or the whole night slips.",
    cta: "Add item",
    secondary: "Open calls",
    fontDisplay: "'Archivo', sans-serif",
    fontSans: "'Archivo', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    wordTrack: ".08em",
    bg: "#EDEEEA",
    card: "#FBFBF9",
    strip: "#E7E8E3",
    line: "#D3D5CE",
    ink: "#171A18",
    body: "#4E534E",
    meta: "#6A6F69",
    headBg: "#1D211F",
    headInk: "#F0F1ED",
    headMeta: "#8D938C",
    avatarBg: "#2E332F",
    accent: "oklch(0.82 0.19 120)",
    accentInk: "oklch(0.42 0.09 130)",
    btnInk: "#171A18",
    tagBg: "oklch(0.93 0.06 120)",
    tagInk: "oklch(0.4 0.09 130)",
    okInk: "oklch(0.44 0.1 140)",
    warnBg: "oklch(0.94 0.08 85)",
    warnInk: "oklch(0.48 0.13 70)",
    star: "oklch(0.66 0.14 80)",
    photoFill:
      "repeating-linear-gradient(90deg, #E2E4DE 0 2px, #EDEEEA 2px 9px)",
    frameRadius: "6px",
    cardRadius: "6px",
    pillRadius: "4px",
    chipRadius: "4px",
    swatches: ["#1D211F", "oklch(0.82 0.19 120)", "oklch(0.48 0.13 70)"],
  },
  {
    key: "postcard",
    name: "Postcard",
    blurb:
      "Family trips and slower holidays. Bleached paper, deep teal, apricot accent, roomier labels for reading aloud.",
    wordmark: "Postcard",
    typeNote: "Fraunces · Bricolage",
    strapline: "Five of us, five nights",
    countdown: "Here now",
    dayTitle: "Landing and the Loop",
    tag: "Dinner",
    bookingLabel: "Table booked",
    itemNote:
      "Deep dish takes forty-five minutes to bake, so order together the moment everyone is seated.",
    cta: "Add to this day",
    secondary: "To decide",
    fontDisplay: "'Fraunces', serif",
    fontSans: "'Bricolage Grotesque', sans-serif",
    fontMono: "'Space Grotesk', sans-serif",
    wordTrack: ".01em",
    bg: "#F6F1E6",
    card: "#FFFCF5",
    strip: "#F1EADA",
    line: "#E5DCC7",
    ink: "#173A3C",
    body: "#4E625F",
    meta: "#75837E",
    headBg: "#12484B",
    headInk: "#F6F1E6",
    headMeta: "#9DBCBB",
    avatarBg: "#1C5C60",
    accent: "oklch(0.72 0.14 55)",
    accentInk: "oklch(0.48 0.11 45)",
    btnInk: "#1B2E2C",
    tagBg: "oklch(0.94 0.05 55)",
    tagInk: "oklch(0.47 0.11 45)",
    okInk: "oklch(0.46 0.1 165)",
    warnBg: "oklch(0.95 0.06 45)",
    warnInk: "oklch(0.5 0.13 40)",
    star: "oklch(0.7 0.14 70)",
    photoFill:
      "repeating-linear-gradient(135deg, #EDE4CF 0 10px, #F4EEE0 10px 20px)",
    frameRadius: "20px",
    cardRadius: "16px",
    pillRadius: "12px",
    chipRadius: "14px",
    swatches: ["#12484B", "oklch(0.72 0.14 55)", "oklch(0.46 0.1 165)"],
  },
];

export const DEFAULT_THEME_KEY = "cherry";

export function getTheme(key: string): Theme {
  return THEMES.find((t) => t.key === key) ?? THEMES[0];
}
